shortcut:
  about: Q
  auto_save: X
  change_output_dir: Shift+Z
  clear: Ctrl+Shift+Z
  clear_label: ''
  clear_recent: ''
  close: ''
  del_active_point: Backspace
  del_active_polygon: Ctrl+Backspace
  edit_shortcuts: E
  finish_object: Space
  grid_ann: ''
  largest_component: ''
  load_label: ''
  load_param: Ctrl+M
  open_folder: Shift+A
  open_image: Ctrl+A
  quick_start: ''
  quit: ''
  redo: Ctrl+Y
  save: ''
  save_as: ''
  save_color: ''
  save_json: ''
  save_label: ''
  turn_next: F
  turn_prev: S
  undo: Ctrl+Z
